/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardapp;

import java.awt.Color;
import java.io.File;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import repository.*;
import utils.MapCustom;

/**
 *
 * @author KeepToo
 */
public class AdminDashboard extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    AdminRepository adminRepository;
    SalesRepository salesRepository;
    LayananRepository layananRepository;
    InformasiPerusahaanRepository informasiPerusahaanRepository;
    public AdminDashboard() {
        initComponents();
        adminRepository = new AdminRepository();
        salesRepository = new SalesRepository();
        layananRepository = new LayananRepository();
        informasiPerusahaanRepository = new InformasiPerusahaanRepository();
        btn_nav_konfig.setVisible(false);
        selectMenu("dashboard");
    }
    int infoId;
    private void selectMenu(String menu) {
        panel_dashboard.setVisible(menu.equals("dashboard"));
        Map<String, JPanel> mapPanel = MapCustom.of("admin", panel_admin, "sales", panel_sales, "layanan", panel_layanan, "konfig", panel_konfig);
        Map<String, JPanel> mapBtnNav = MapCustom.of("admin", btn_nav_admin, "sales", btn_nav_sales, "layanan", btn_nav_layanan, "konfig", btn_nav_konfig);
//        Map<String, JPanel> mapIndicator = MapCustom.of("admin", Indicator1, "sales", Indicator2, "layanan", Indicator3, "konfig", Indicator4);
        Map<String, Repository> mapRepositories = MapCustom.of("admin", adminRepository, "sales", salesRepository, "layanan", layananRepository, "konfig", informasiPerusahaanRepository);
        Map<String, JTable> mapTable = MapCustom.of("admin", tbl_admin, "sales", tbl_sales, "layanan", tbl_layanan);
        for (String key : mapPanel.keySet()) {
            if (key.equals(menu)) {
                mapPanel.get(key).setVisible(true);
                onClick(mapBtnNav.get(key));
//                mapIndicator.get(key).setOpaque(true);
                if (key.equals("konfig")) {
                    model.InformasiPerusahaan info = (model.InformasiPerusahaan) mapRepositories.get(key).first();
                    if (info != null) {
                        infoId = info.getId();
                        txtNamaPerusahaanKonfigurasi.setText(info.getNamaPerusahaan());
                        txtAlamatKonfigurasi.setText(info.getAlamat());
                        txtNoTeleponKonfigurasi.setText(info.getNoTlp());
                        txtEmailKonfigurasi.setText(info.getEmail());
                    }
                } else {
                    mapRepositories.get(key).renderDataTable(mapTable.get(key));
                }
            } else {
                mapPanel.get(key).setVisible(false);
                onLeaveClick(mapBtnNav.get(key));
//                mapIndicator.get(key).setOpaque(false);
            }
        }
    }
    void clearFormAdmin(){
        txtNamaAdmin.setText("");
        txtEmailAdmin.setText("");
        txtPasswordAdmin.setText("");
        tbl_admin.clearSelection();
    }
    void clearFormSales(){
        txtNamaSales.setText("");
        txtEmailSales.setText("");
        txtPasswordSales.setText("");
        tbl_sales.clearSelection();
    }
    void clearFormLayanan(){
        txtNamaLayanan.setText("");
        txtDeskripsiLayanan.setText("");
        txtHargaLayanan.setText("");
        tbl_layanan.clearSelection();
    }
    void logout(){
        this.dispose();
        new Login().setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_nav_admin = new javax.swing.JPanel();
        lbl_admin = new javax.swing.JLabel();
        btn_nav_sales = new javax.swing.JPanel();
        lbl_pelanggan = new javax.swing.JLabel();
        btn_nav_layanan = new javax.swing.JPanel();
        lbl_transaksi = new javax.swing.JLabel();
        btn_nav_konfig = new javax.swing.JPanel();
        lbl_report = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        panel_dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nav_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        panel_admin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panel_tabel1 = new javax.swing.JScrollPane();
        tbl_admin = new javax.swing.JTable();
        btn_tambah1 = new com.k33ptoo.components.KButton();
        btn_edit1 = new com.k33ptoo.components.KButton();
        btn_hapus1 = new com.k33ptoo.components.KButton();
        btn_hapus2 = new com.k33ptoo.components.KButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        txtPasswordAdmin = new javax.swing.JPasswordField();
        txtNamaAdmin = new javax.swing.JTextField();
        txtEmailAdmin = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        btn_tambah_pelanggan4 = new com.k33ptoo.components.KButton();
        panel_sales = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panel_tabel2 = new javax.swing.JScrollPane();
        tbl_sales = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        btn_tambah5 = new com.k33ptoo.components.KButton();
        btn_edit5 = new com.k33ptoo.components.KButton();
        btn_hapus9 = new com.k33ptoo.components.KButton();
        btn_hapus10 = new com.k33ptoo.components.KButton();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        txtPasswordSales = new javax.swing.JPasswordField();
        txtNamaSales = new javax.swing.JTextField();
        txtEmailSales = new javax.swing.JTextField();
        btn_tambah_pelanggan5 = new com.k33ptoo.components.KButton();
        panel_layanan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panel_tabel3 = new javax.swing.JScrollPane();
        tbl_layanan = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        btn_tambah6 = new com.k33ptoo.components.KButton();
        btn_edit6 = new com.k33ptoo.components.KButton();
        btn_hapus11 = new com.k33ptoo.components.KButton();
        btn_hapus12 = new com.k33ptoo.components.KButton();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        txtNamaLayanan = new javax.swing.JTextField();
        txtDeskripsiLayanan = new javax.swing.JTextField();
        txtHargaLayanan = new javax.swing.JTextField();
        btn_tambah_pelanggan6 = new com.k33ptoo.components.KButton();
        panel_konfig = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_tambah4 = new com.k33ptoo.components.KButton();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        jButton5 = new javax.swing.JButton();
        txtNamaPerusahaanKonfigurasi = new javax.swing.JTextField();
        txtAlamatKonfigurasi = new javax.swing.JTextField();
        txtNoTeleponKonfigurasi = new javax.swing.JTextField();
        label19 = new java.awt.Label();
        txtEmailKonfigurasi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI CUSTOMER DATA MANAGEMENT");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nav_admin.setBackground(new java.awt.Color(255, 255, 255));
        btn_nav_admin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_nav_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nav_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nav_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nav_adminMouseExited(evt);
            }
        });

        lbl_admin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_admin.setText("Admin");
        lbl_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_adminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_nav_adminLayout = new javax.swing.GroupLayout(btn_nav_admin);
        btn_nav_admin.setLayout(btn_nav_adminLayout);
        btn_nav_adminLayout.setHorizontalGroup(
            btn_nav_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_nav_adminLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_admin)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        btn_nav_adminLayout.setVerticalGroup(
            btn_nav_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_nav_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_nav_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 190, -1));

        btn_nav_sales.setBackground(new java.awt.Color(255, 255, 255));
        btn_nav_sales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_nav_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nav_salesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nav_salesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nav_salesMouseExited(evt);
            }
        });

        lbl_pelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_pelanggan.setText("Sales");
        lbl_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pelangganMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_nav_salesLayout = new javax.swing.GroupLayout(btn_nav_sales);
        btn_nav_sales.setLayout(btn_nav_salesLayout);
        btn_nav_salesLayout.setHorizontalGroup(
            btn_nav_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_nav_salesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_pelanggan)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        btn_nav_salesLayout.setVerticalGroup(
            btn_nav_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_nav_salesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_nav_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 227, 190, -1));

        btn_nav_layanan.setBackground(new java.awt.Color(255, 255, 255));
        btn_nav_layanan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_nav_layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nav_layananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nav_layananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nav_layananMouseExited(evt);
            }
        });

        lbl_transaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_transaksi.setText("Layanan");
        lbl_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_transaksiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_nav_layananLayout = new javax.swing.GroupLayout(btn_nav_layanan);
        btn_nav_layanan.setLayout(btn_nav_layananLayout);
        btn_nav_layananLayout.setHorizontalGroup(
            btn_nav_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_nav_layananLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_transaksi)
                .addGap(0, 83, Short.MAX_VALUE))
        );
        btn_nav_layananLayout.setVerticalGroup(
            btn_nav_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_nav_layananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_nav_layanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 279, 190, -1));

        btn_nav_konfig.setBackground(new java.awt.Color(255, 255, 255));
        btn_nav_konfig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_nav_konfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nav_konfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nav_konfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nav_konfigMouseExited(evt);
            }
        });

        lbl_report.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_report.setText("Konfigurasi");
        lbl_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_reportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_nav_konfigLayout = new javax.swing.GroupLayout(btn_nav_konfig);
        btn_nav_konfig.setLayout(btn_nav_konfigLayout);
        btn_nav_konfigLayout.setHorizontalGroup(
            btn_nav_konfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_nav_konfigLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_report)
                .addGap(0, 64, Short.MAX_VALUE))
        );
        btn_nav_konfigLayout.setVerticalGroup(
            btn_nav_konfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_nav_konfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_report, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_nav_konfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, -1));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 39, -1, -1));

        jLabel21.setFont(new java.awt.Font("Impact", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("ADMIN DASHBOARD");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, -1));

        jPanel14.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 530));

        panel_dashboard.setBackground(new java.awt.Color(247, 247, 247));
        panel_dashboard.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_dashboardMouseDragged(evt);
            }
        });
        panel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_dashboardMousePressed(evt);
            }
        });
        panel_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("APLIKASI PENGELOLAAN DATA PELANGGAN");
        panel_dashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 410, 37));

        nav_panel.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Jumlah Layanan");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("500");

        jPanel11.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("50");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, -1, -1));

        jPanel10.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Jumlah Sales");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("$2000");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, 75, -1));

        jPanel12.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("Jumlah Admin");

        javax.swing.GroupLayout nav_panelLayout = new javax.swing.GroupLayout(nav_panel);
        nav_panel.setLayout(nav_panelLayout);
        nav_panelLayout.setHorizontalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nav_panelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_panelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        nav_panelLayout.setVerticalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nav_panelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nav_panelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nav_panelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panel_dashboard.add(nav_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 480, 150));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("X ");
        jButton9.setBorder(null);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panel_dashboard.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 190, 40));

        getContentPane().add(panel_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 770, 530));

        panel_admin.setBackground(new java.awt.Color(247, 247, 247));
        panel_admin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_adminMouseDragged(evt);
            }
        });
        panel_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_adminMousePressed(evt);
            }
        });
        panel_admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("DATA ADMIN APLIKASI");
        panel_admin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 410, 37));

        panel_tabel1.setBackground(new java.awt.Color(247, 247, 247));
        panel_tabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_admin.setBackground(new java.awt.Color(247, 247, 247));
        tbl_admin.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Allan", "XLS", "2hrs", "$200"},
                {"Brian", "React", "1hr", "$100 per hr"},
                {"Romeo", "C#", "3 Days", "$1000"},
                {"Alex", "C++ ", "10 hrs", "$50 per hr"}
            },
            new String [] {
                "Name", "Project", "Time", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_admin.setGridColor(new java.awt.Color(247, 247, 247));
        tbl_admin.setSelectionBackground(new java.awt.Color(96, 83, 150));
        tbl_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_adminMouseClicked(evt);
            }
        });
        panel_tabel1.setViewportView(tbl_admin);

        panel_admin.add(panel_tabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 710, 240));

        btn_tambah1.setText("Tambah");
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });
        panel_admin.add(btn_tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 83, 29));

        btn_edit1.setText("Edit");
        btn_edit1.setkStartColor(new java.awt.Color(0, 51, 153));
        btn_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit1ActionPerformed(evt);
            }
        });
        panel_admin.add(btn_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 83, 29));

        btn_hapus1.setText("Hapus");
        btn_hapus1.setkStartColor(new java.awt.Color(255, 0, 0));
        btn_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus1ActionPerformed(evt);
            }
        });
        panel_admin.add(btn_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 83, 29));

        btn_hapus2.setText("Bersihkan");
        btn_hapus2.setkStartColor(new java.awt.Color(255, 102, 51));
        btn_hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus2ActionPerformed(evt);
            }
        });
        panel_admin.add(btn_hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 83, 29));

        label1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label1.setText("Password");
        panel_admin.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        label2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label2.setText("Nama");
        panel_admin.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        label3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label3.setText("Email");
        panel_admin.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        panel_admin.add(txtPasswordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 320, -1));

        txtNamaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaAdminActionPerformed(evt);
            }
        });
        panel_admin.add(txtNamaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 320, -1));

        txtEmailAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAdminActionPerformed(evt);
            }
        });
        panel_admin.add(txtEmailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 320, -1));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("X ");
        jButton8.setBorder(null);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panel_admin.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 190, 40));

        btn_tambah_pelanggan4.setText("Cetak");
        btn_tambah_pelanggan4.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_tambah_pelanggan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_pelanggan4ActionPerformed(evt);
            }
        });
        panel_admin.add(btn_tambah_pelanggan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 83, 29));

        getContentPane().add(panel_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 770, 530));

        panel_sales.setBackground(new java.awt.Color(247, 247, 247));
        panel_sales.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_salesMouseDragged(evt);
            }
        });
        panel_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_salesMousePressed(evt);
            }
        });
        panel_sales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("DATA SALES APLIKASI");
        panel_sales.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 410, 37));

        panel_tabel2.setBackground(new java.awt.Color(247, 247, 247));
        panel_tabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_sales.setBackground(new java.awt.Color(247, 247, 247));
        tbl_sales.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Allan", "XLS", "2hrs", "$200"},
                {"Brian", "React", "1hr", "$100 per hr"},
                {"Romeo", "C#", "3 Days", "$1000"},
                {"Alex", "C++ ", "10 hrs", "$50 per hr"}
            },
            new String [] {
                "Name", "Project", "Time", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_sales.setGridColor(new java.awt.Color(247, 247, 247));
        tbl_sales.setSelectionBackground(new java.awt.Color(96, 83, 150));
        tbl_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_salesMouseClicked(evt);
            }
        });
        panel_tabel2.setViewportView(tbl_sales);

        panel_sales.add(panel_tabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 710, 320));

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("X ");
        jButton7.setBorder(null);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel_sales.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 190, 40));

        btn_tambah5.setText("Tambah");
        btn_tambah5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah5ActionPerformed(evt);
            }
        });
        panel_sales.add(btn_tambah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 83, 29));

        btn_edit5.setText("Edit");
        btn_edit5.setkStartColor(new java.awt.Color(0, 51, 153));
        btn_edit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit5ActionPerformed(evt);
            }
        });
        panel_sales.add(btn_edit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 83, 29));

        btn_hapus9.setText("Hapus");
        btn_hapus9.setkStartColor(new java.awt.Color(255, 0, 0));
        btn_hapus9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus9ActionPerformed(evt);
            }
        });
        panel_sales.add(btn_hapus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 83, 29));

        btn_hapus10.setText("Bersihkan");
        btn_hapus10.setkStartColor(new java.awt.Color(255, 102, 51));
        btn_hapus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus10ActionPerformed(evt);
            }
        });
        panel_sales.add(btn_hapus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 83, 29));

        label13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label13.setText("Password");
        panel_sales.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        label14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label14.setText("Nama");
        panel_sales.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        label15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label15.setText("Email");
        panel_sales.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        panel_sales.add(txtPasswordSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 320, -1));

        txtNamaSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSalesActionPerformed(evt);
            }
        });
        panel_sales.add(txtNamaSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 320, -1));

        txtEmailSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailSalesActionPerformed(evt);
            }
        });
        panel_sales.add(txtEmailSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 320, -1));

        btn_tambah_pelanggan5.setText("Cetak");
        btn_tambah_pelanggan5.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_tambah_pelanggan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_pelanggan5ActionPerformed(evt);
            }
        });
        panel_sales.add(btn_tambah_pelanggan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 83, 29));

        getContentPane().add(panel_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 770, 530));

        panel_layanan.setBackground(new java.awt.Color(247, 247, 247));
        panel_layanan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_layananMouseDragged(evt);
            }
        });
        panel_layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_layananMousePressed(evt);
            }
        });
        panel_layanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("DATA LAYANAN APLIKASI");
        panel_layanan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 410, 37));

        panel_tabel3.setBackground(new java.awt.Color(247, 247, 247));
        panel_tabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbl_layanan.setBackground(new java.awt.Color(247, 247, 247));
        tbl_layanan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_layanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Allan", "XLS", "2hrs", "$200"},
                {"Brian", "React", "1hr", "$100 per hr"},
                {"Romeo", "C#", "3 Days", "$1000"},
                {"Alex", "C++ ", "10 hrs", "$50 per hr"}
            },
            new String [] {
                "Name", "Project", "Time", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_layanan.setGridColor(new java.awt.Color(247, 247, 247));
        tbl_layanan.setSelectionBackground(new java.awt.Color(96, 83, 150));
        tbl_layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_layananMouseClicked(evt);
            }
        });
        panel_tabel3.setViewportView(tbl_layanan);

        panel_layanan.add(panel_tabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 710, 320));

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("X ");
        jButton6.setBorder(null);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel_layanan.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 190, 40));

        btn_tambah6.setText("Tambah");
        btn_tambah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah6ActionPerformed(evt);
            }
        });
        panel_layanan.add(btn_tambah6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 83, 29));

        btn_edit6.setText("Edit");
        btn_edit6.setkStartColor(new java.awt.Color(0, 51, 153));
        btn_edit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit6ActionPerformed(evt);
            }
        });
        panel_layanan.add(btn_edit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 83, 29));

        btn_hapus11.setText("Hapus");
        btn_hapus11.setkStartColor(new java.awt.Color(255, 0, 0));
        btn_hapus11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus11ActionPerformed(evt);
            }
        });
        panel_layanan.add(btn_hapus11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 83, 29));

        btn_hapus12.setText("Bersihkan");
        btn_hapus12.setkStartColor(new java.awt.Color(255, 102, 51));
        btn_hapus12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus12ActionPerformed(evt);
            }
        });
        panel_layanan.add(btn_hapus12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 83, 29));

        label16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label16.setText("Harga");
        panel_layanan.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        label17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label17.setText("Nama Layanan");
        panel_layanan.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        label18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label18.setText("Deskripsi");
        panel_layanan.add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtNamaLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaLayananActionPerformed(evt);
            }
        });
        panel_layanan.add(txtNamaLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 320, -1));

        txtDeskripsiLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeskripsiLayananActionPerformed(evt);
            }
        });
        panel_layanan.add(txtDeskripsiLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 320, -1));

        txtHargaLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaLayananActionPerformed(evt);
            }
        });
        panel_layanan.add(txtHargaLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 320, -1));

        btn_tambah_pelanggan6.setText("Cetak");
        btn_tambah_pelanggan6.setkStartColor(new java.awt.Color(204, 0, 204));
        btn_tambah_pelanggan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_pelanggan6ActionPerformed(evt);
            }
        });
        panel_layanan.add(btn_tambah_pelanggan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 83, 29));

        getContentPane().add(panel_layanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 770, 530));

        panel_konfig.setBackground(new java.awt.Color(247, 247, 247));
        panel_konfig.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_konfigMouseDragged(evt);
            }
        });
        panel_konfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_konfigMousePressed(evt);
            }
        });
        panel_konfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("DATA KONFIGURASI");
        panel_konfig.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 23, 410, 37));

        btn_tambah4.setText("Simpan");
        btn_tambah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah4ActionPerformed(evt);
            }
        });
        panel_konfig.add(btn_tambah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 83, 29));

        label10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label10.setText("No Telepon");
        panel_konfig.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        label11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label11.setText("Nama Perusahaan");
        panel_konfig.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        label12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label12.setText("Alamat");
        panel_konfig.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("X ");
        jButton5.setBorder(null);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_konfig.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 190, 40));

        txtNamaPerusahaanKonfigurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPerusahaanKonfigurasiActionPerformed(evt);
            }
        });
        panel_konfig.add(txtNamaPerusahaanKonfigurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 320, -1));

        txtAlamatKonfigurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatKonfigurasiActionPerformed(evt);
            }
        });
        panel_konfig.add(txtAlamatKonfigurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 320, -1));

        txtNoTeleponKonfigurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTeleponKonfigurasiActionPerformed(evt);
            }
        });
        panel_konfig.add(txtNoTeleponKonfigurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 320, -1));

        label19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label19.setText("Email");
        panel_konfig.add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtEmailKonfigurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailKonfigurasiActionPerformed(evt);
            }
        });
        panel_konfig.add(txtEmailKonfigurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 320, -1));

        getContentPane().add(panel_konfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 770, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nav_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_adminMouseClicked
        selectMenu("admin");
    }//GEN-LAST:event_btn_nav_adminMouseClicked

    private void btn_nav_salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_salesMouseClicked
        selectMenu("sales");
    }//GEN-LAST:event_btn_nav_salesMouseClicked

    private void btn_nav_layananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_layananMouseClicked
        selectMenu("layanan");
    }//GEN-LAST:event_btn_nav_layananMouseClicked

    private void btn_nav_konfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_konfigMouseClicked
        selectMenu("konfig");
    }//GEN-LAST:event_btn_nav_konfigMouseClicked

    private void btn_nav_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_adminMouseEntered
        // TODO add your handling code here:
 
    }//GEN-LAST:event_btn_nav_adminMouseEntered

    private void btn_nav_salesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_salesMouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btn_nav_salesMouseEntered

    private void btn_nav_layananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_layananMouseEntered
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btn_nav_layananMouseEntered

    private void btn_nav_konfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_konfigMouseEntered
        // TODO add your handling code here:]
         
    }//GEN-LAST:event_btn_nav_konfigMouseEntered

    private void btn_nav_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_adminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nav_adminMouseExited

    private void btn_nav_salesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_salesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nav_salesMouseExited

    private void btn_nav_layananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_layananMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nav_layananMouseExited

    private void btn_nav_konfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nav_konfigMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nav_konfigMouseExited

    private void panel_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashboardMousePressed
        // TODO add your handling code here:
          xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_panel_dashboardMousePressed

    private void panel_dashboardMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashboardMouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_panel_dashboardMouseDragged

    private void lbl_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_adminMouseClicked
       
    }//GEN-LAST:event_lbl_adminMouseClicked

    private void lbl_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pelangganMouseClicked
        
    }//GEN-LAST:event_lbl_pelangganMouseClicked

    private void lbl_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_transaksiMouseClicked
        
    }//GEN-LAST:event_lbl_transaksiMouseClicked

    private void lbl_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_reportMouseClicked
        
    }//GEN-LAST:event_lbl_reportMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        selectMenu("dashboard");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void btn_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit1ActionPerformed
        model.Admin admin = new model.Admin();
        admin.setNama(txtNamaAdmin.getText());
        admin.setEmail(txtEmailAdmin.getText());
        admin.setPassword(new String(txtPasswordAdmin.getPassword()));
        try {
            adminRepository.update(admin.toMap(), MapCustom.of("id_admin", adminRepository.selectedData(tbl_admin).getIdAdmin()));
            clearFormAdmin();
            selectMenu("admin");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data Admin! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_edit1ActionPerformed

    private void btn_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus1ActionPerformed
        try {
            adminRepository.delete(MapCustom.of("id_admin", adminRepository.selectedData(tbl_admin).getIdAdmin()));
            clearFormAdmin();
            selectMenu("admin");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data Admin! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_hapus1ActionPerformed

    private void panel_adminMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_adminMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_adminMouseDragged

    private void panel_adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_adminMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_adminMousePressed

    private void btn_hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus2ActionPerformed
        clearFormAdmin();
    }//GEN-LAST:event_btn_hapus2ActionPerformed

    private void panel_salesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_salesMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_salesMouseDragged

    private void panel_salesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_salesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_salesMousePressed

    private void panel_layananMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_layananMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_layananMouseDragged

    private void panel_layananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_layananMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_layananMousePressed

    private void panel_konfigMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_konfigMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_konfigMouseDragged

    private void panel_konfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_konfigMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_konfigMousePressed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        model.Admin admin = new model.Admin();
        admin.setNama(txtNamaAdmin.getText());
        admin.setEmail(txtEmailAdmin.getText());
        admin.setPassword(new String(txtPasswordAdmin.getPassword()));
        try {
            adminRepository.save(admin);
            clearFormAdmin();
            selectMenu("admin");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data Admin! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void txtNamaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaAdminActionPerformed

    private void txtEmailAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAdminActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        logout();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        logout();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        logout();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        logout();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        logout();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tbl_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_adminMouseClicked
        model.Admin admin = adminRepository.selectedData(tbl_admin);
        txtNamaAdmin.setText(admin.getNama());
        txtEmailAdmin.setText(admin.getEmail());
        txtPasswordAdmin.setText(admin.getPassword());
    }//GEN-LAST:event_tbl_adminMouseClicked

    private void tbl_salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_salesMouseClicked
        model.Sales sales = salesRepository.selectedData(tbl_sales);
        txtNamaSales.setText(sales.getNama());
        txtEmailSales.setText(sales.getEmail());
        txtPasswordSales.setText(sales.getPassword());
    }//GEN-LAST:event_tbl_salesMouseClicked

    private void tbl_layananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_layananMouseClicked
        model.Layanan layanan = layananRepository.selectedData(tbl_layanan);
        txtNamaLayanan.setText(layanan.getNama());
        txtDeskripsiLayanan.setText(layanan.getDeskripsi());
        System.out.println(layanan.getHarga());
        txtHargaLayanan.setText(Integer.toString(layanan.getHarga()));
    }//GEN-LAST:event_tbl_layananMouseClicked

    private void btn_tambah5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah5ActionPerformed
        model.Sales sales = new model.Sales();
        sales.setNama(txtNamaSales.getText());
        sales.setEmail(txtEmailSales.getText());
        sales.setPassword(new String(txtPasswordSales.getPassword()));
        try {
            salesRepository.save(sales);
            clearFormSales();
            selectMenu("sales");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data Sales! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_tambah5ActionPerformed

    private void btn_edit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit5ActionPerformed
        model.Sales sales = new model.Sales();
        sales.setNama(txtNamaSales.getText());
        sales.setEmail(txtEmailSales.getText());
        sales.setPassword(new String(txtPasswordSales.getPassword()));
        try {
            salesRepository.update(sales.toMap(), MapCustom.of("id_sales", salesRepository.selectedData(tbl_sales).getIdSales()));
            clearFormSales();
            selectMenu("sales");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data Sales! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_edit5ActionPerformed

    private void btn_hapus9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus9ActionPerformed
        try {
            salesRepository.delete(MapCustom.of("id_sales", salesRepository.selectedData(tbl_sales).getIdSales()));
            clearFormSales();
            selectMenu("sales");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data Sales! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_hapus9ActionPerformed

    private void btn_hapus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus10ActionPerformed
        clearFormSales();
    }//GEN-LAST:event_btn_hapus10ActionPerformed

    private void txtNamaSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSalesActionPerformed

    private void txtEmailSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailSalesActionPerformed

    private void btn_tambah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah6ActionPerformed
        model.Layanan layanan = new model.Layanan();
        layanan.setNama(txtNamaLayanan.getText());
        layanan.setDeskripsi(txtDeskripsiLayanan.getText());
        try {
            layanan.setHarga(Integer.parseInt(txtHargaLayanan.getText()));
            layananRepository.save(layanan);
            clearFormLayanan();
            selectMenu("layanan");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data Layanan! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_tambah6ActionPerformed

    private void btn_edit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit6ActionPerformed
        model.Layanan layanan = new model.Layanan();
        layanan.setNama(txtNamaLayanan.getText());
        layanan.setDeskripsi(txtDeskripsiLayanan.getText());
        try {
            layanan.setHarga(Integer.parseInt(txtHargaLayanan.getText()));
            layananRepository.update(layanan.toMap(), MapCustom.of("id_layanan", layananRepository.selectedData(tbl_layanan).getIdLayanan()));
            clearFormLayanan();
            selectMenu("layanan");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data Layanan! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_edit6ActionPerformed

    private void btn_hapus11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus11ActionPerformed
        try {
            layananRepository.delete(MapCustom.of("id_layanan", layananRepository.selectedData(tbl_layanan).getIdLayanan()));
            clearFormLayanan();
            selectMenu("layanan");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data Layanan! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_hapus11ActionPerformed

    private void btn_hapus12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus12ActionPerformed
        clearFormLayanan();
    }//GEN-LAST:event_btn_hapus12ActionPerformed

    private void txtNamaLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLayananActionPerformed

    private void txtDeskripsiLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeskripsiLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeskripsiLayananActionPerformed

    private void txtHargaLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaLayananActionPerformed

    private void txtNamaPerusahaanKonfigurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPerusahaanKonfigurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPerusahaanKonfigurasiActionPerformed

    private void txtAlamatKonfigurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatKonfigurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatKonfigurasiActionPerformed

    private void txtNoTeleponKonfigurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTeleponKonfigurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTeleponKonfigurasiActionPerformed

    private void txtEmailKonfigurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailKonfigurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKonfigurasiActionPerformed

    private void btn_tambah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah4ActionPerformed
        model.InformasiPerusahaan info = new model.InformasiPerusahaan();
        info.setNamaPerusahaan(txtNamaPerusahaanKonfigurasi.getText());
        info.setAlamat(txtAlamatKonfigurasi.getText());
        info.setNoTlp(txtNoTeleponKonfigurasi.getText());
        info.setEmail(txtEmailKonfigurasi.getText());
        try {
            informasiPerusahaanRepository.update(info.toMap(), MapCustom.of("id", infoId));
            selectMenu("konfig");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data Informasi Perusahaan! : "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_tambah4ActionPerformed

    private void btn_tambah_pelanggan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_pelanggan4ActionPerformed
        try {
            File pelanggan = new File("src/report/admin.jasper");
            JasperPrint jp = JasperFillManager.fillReport(pelanggan.getPath(), null, Koneksi.Koneksi.koneksidb());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_tambah_pelanggan4ActionPerformed

    private void btn_tambah_pelanggan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_pelanggan5ActionPerformed
        try {
            File pelanggan = new File("src/report/sales.jasper");
            JasperPrint jp = JasperFillManager.fillReport(pelanggan.getPath(), null, Koneksi.Koneksi.koneksidb());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_tambah_pelanggan5ActionPerformed

    private void btn_tambah_pelanggan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_pelanggan6ActionPerformed
        try {
            File pelanggan = new File("src/report/layanan.jasper");
            JasperPrint jp = JasperFillManager.fillReport(pelanggan.getPath(), null, Koneksi.Koneksi.koneksidb());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_tambah_pelanggan6ActionPerformed

    int xx ,xy;
    
       
    //bad idea
    
    
    private void onClick(JPanel panel)
    {
        panel.setBackground(new Color(102,153,255));
    }
    
     private void onLeaveClick(JPanel panel)
    {
        panel.setBackground(Color.white);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_edit1;
    private com.k33ptoo.components.KButton btn_edit5;
    private com.k33ptoo.components.KButton btn_edit6;
    private com.k33ptoo.components.KButton btn_hapus1;
    private com.k33ptoo.components.KButton btn_hapus10;
    private com.k33ptoo.components.KButton btn_hapus11;
    private com.k33ptoo.components.KButton btn_hapus12;
    private com.k33ptoo.components.KButton btn_hapus2;
    private com.k33ptoo.components.KButton btn_hapus9;
    private javax.swing.JPanel btn_nav_admin;
    private javax.swing.JPanel btn_nav_konfig;
    private javax.swing.JPanel btn_nav_layanan;
    private javax.swing.JPanel btn_nav_sales;
    private com.k33ptoo.components.KButton btn_tambah1;
    private com.k33ptoo.components.KButton btn_tambah4;
    private com.k33ptoo.components.KButton btn_tambah5;
    private com.k33ptoo.components.KButton btn_tambah6;
    private com.k33ptoo.components.KButton btn_tambah_pelanggan4;
    private com.k33ptoo.components.KButton btn_tambah_pelanggan5;
    private com.k33ptoo.components.KButton btn_tambah_pelanggan6;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel lbl_admin;
    private javax.swing.JLabel lbl_pelanggan;
    private javax.swing.JLabel lbl_report;
    private javax.swing.JLabel lbl_transaksi;
    private javax.swing.JPanel nav_panel;
    private javax.swing.JPanel panel_admin;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_konfig;
    private javax.swing.JPanel panel_layanan;
    private javax.swing.JPanel panel_sales;
    private javax.swing.JScrollPane panel_tabel1;
    private javax.swing.JScrollPane panel_tabel2;
    private javax.swing.JScrollPane panel_tabel3;
    private javax.swing.JTable tbl_admin;
    private javax.swing.JTable tbl_layanan;
    private javax.swing.JTable tbl_sales;
    private javax.swing.JTextField txtAlamatKonfigurasi;
    private javax.swing.JTextField txtDeskripsiLayanan;
    private javax.swing.JTextField txtEmailAdmin;
    private javax.swing.JTextField txtEmailKonfigurasi;
    private javax.swing.JTextField txtEmailSales;
    private javax.swing.JTextField txtHargaLayanan;
    private javax.swing.JTextField txtNamaAdmin;
    private javax.swing.JTextField txtNamaLayanan;
    private javax.swing.JTextField txtNamaPerusahaanKonfigurasi;
    private javax.swing.JTextField txtNamaSales;
    private javax.swing.JTextField txtNoTeleponKonfigurasi;
    private javax.swing.JPasswordField txtPasswordAdmin;
    private javax.swing.JPasswordField txtPasswordSales;
    // End of variables declaration//GEN-END:variables
}
